"""CPU F32 oracle for the Transformers shared-expert output gate formula.

Local Transformers 5.2 qwen3_5_moe/modeling_qwen3_5_moe.py:
    F.sigmoid(self.shared_expert_gate(hidden_states)) * shared_expert_output
Only the broadcast multiply is tested here; projection/model code is out of scope.
Generate a compact periodic table rather than storing repeated 2048-wide rows.
The checked-in Rust table makes GPU tests independent of Python/torch installs.
"""
from pathlib import Path
import torch
import transformers

torch.set_num_threads(1)
x = torch.tensor([1.00390625, -2.25, 0.0, -0.0, 0.375, 3.5, -5.25, 0.0078125], dtype=torch.float32)
g = torch.tensor([0.0, -0.0, -100.0, -7.3, -0.37, 0.37, 7.3, 100.0, 1.125], dtype=torch.float32)
y = torch.nn.functional.sigmoid(g[:, None]) * x[None, :]
silu_y = (torch.nn.functional.sigmoid(g[:, None]) * g[:, None]) * x[None, :]

def array(xs):
    return '[' + ', '.join(repr(v) for v in xs) + ']'

def matrix(name, xs):
    return f'pub const {name}: [[f32; 8]; 9] = [\n' + ''.join('    ' + array(row) + ',\n' for row in xs) + '];\n'

out = f'// Generated by row_gate_reference.py, torch {torch.__version__}, Transformers {transformers.__version__}.\n'
out += '// CPU float32; exact unrounded F32 inputs, including signed zero.\n'
out += '#![allow(clippy::excessive_precision)]\n'
out += 'pub const INPUT: [f32; 8] = ' + array(x.tolist()) + ';\n'
out += 'pub const GATE: [f32; 9] = ' + array(g.tolist()) + ';\n'
out += matrix('SIGMOID', y.tolist())
out += matrix('SILU', silu_y.tolist())
Path(__file__).with_suffix('.rs').write_text(out)
print('Generated row gate CPU oracle:', torch.__version__, transformers.__version__)
