//! Minimal CUDA Driver API ownership layer used by Ferrule.
//!
//! This module deliberately exposes only the context, stream, event, graph and
//! memory operations required by the backend. Kernel contracts live in the
//! native operator catalog instead of being generated by a Rust device-code
//! framework.

use std::ffi::{CStr, c_char, c_int, c_uint, c_void};
use std::fmt;
use std::marker::PhantomData;

use std::ops::{Deref, DerefMut};
use std::ptr::NonNull;
use std::sync::Arc;

use snafu::Snafu;

pub type DevicePtr = u64;
type CuDevice = c_int;
type CuContext = *mut c_void;
type CuStream = *mut c_void;
type CuEvent = *mut c_void;
type CuGraph = *mut c_void;
type CuGraphExec = *mut c_void;
type CuResult = c_int;

const CUDA_SUCCESS: CuResult = 0;
const CUDA_ERROR_NOT_READY: CuResult = 600;
const CU_STREAM_NON_BLOCKING: c_uint = 1;
const CU_EVENT_DEFAULT: c_uint = 0;
const CU_EVENT_DISABLE_TIMING: c_uint = 2;
const CU_STREAM_CAPTURE_MODE_RELAXED: c_int = 2;
const CU_MEM_ATTACH_GLOBAL: c_uint = 1;
const CU_MEM_ADVISE_SET_READ_MOSTLY: c_int = 1;

#[link(name = "cuda")]
unsafe extern "C" {
    fn cuInit(flags: c_uint) -> CuResult;
    fn cuGetErrorName(error: CuResult, name: *mut *const c_char) -> CuResult;
    fn cuGetErrorString(error: CuResult, description: *mut *const c_char) -> CuResult;
    fn cuDeviceGet(device: *mut CuDevice, ordinal: c_int) -> CuResult;
    fn cuDeviceGetName(name: *mut c_char, len: c_int, device: CuDevice) -> CuResult;
    fn cuDevicePrimaryCtxRetain(context: *mut CuContext, device: CuDevice) -> CuResult;
    #[link_name = "cuDevicePrimaryCtxRelease_v2"]
    fn cu_device_primary_ctx_release(device: CuDevice) -> CuResult;
    fn cuCtxGetCurrent(context: *mut CuContext) -> CuResult;
    fn cuCtxSetCurrent(context: CuContext) -> CuResult;
    fn cuCtxGetStreamPriorityRange(
        least_priority: *mut c_int,
        greatest_priority: *mut c_int,
    ) -> CuResult;

    fn cuMemGetInfo_v2(free: *mut usize, total: *mut usize) -> CuResult;
    fn cuMemAlloc_v2(ptr: *mut DevicePtr, bytes: usize) -> CuResult;
    fn cuMemAllocManaged(ptr: *mut DevicePtr, bytes: usize, flags: c_uint) -> CuResult;
    fn cuMemFree_v2(ptr: DevicePtr) -> CuResult;
    fn cuMemAllocHost_v2(ptr: *mut *mut c_void, bytes: usize) -> CuResult;
    fn cuMemFreeHost(ptr: *mut c_void) -> CuResult;
    fn cuMemHostGetDevicePointer_v2(
        device_ptr: *mut DevicePtr,
        host_ptr: *mut c_void,
        flags: c_uint,
    ) -> CuResult;
    fn cuMemAdvise(ptr: DevicePtr, bytes: usize, advice: c_int, device: CuDevice) -> CuResult;
    fn cuMemcpyHtoDAsync_v2(
        dst: DevicePtr,
        src: *const c_void,
        bytes: usize,
        stream: CuStream,
    ) -> CuResult;
    fn cuMemcpyDtoHAsync_v2(
        dst: *mut c_void,
        src: DevicePtr,
        bytes: usize,
        stream: CuStream,
    ) -> CuResult;
    fn cuMemcpyDtoDAsync_v2(
        dst: DevicePtr,
        src: DevicePtr,
        bytes: usize,
        stream: CuStream,
    ) -> CuResult;
    fn cuMemsetD8Async(dst: DevicePtr, value: u8, count: usize, stream: CuStream) -> CuResult;
    fn cuMemsetD32Async(dst: DevicePtr, value: u32, count: usize, stream: CuStream) -> CuResult;

    fn cuStreamCreate(stream: *mut CuStream, flags: c_uint) -> CuResult;
    fn cuStreamCreateWithPriority(
        stream: *mut CuStream,
        flags: c_uint,
        priority: c_int,
    ) -> CuResult;
    fn cuStreamGetPriority(stream: CuStream, priority: *mut c_int) -> CuResult;
    fn cuStreamDestroy_v2(stream: CuStream) -> CuResult;
    fn cuStreamSynchronize(stream: CuStream) -> CuResult;
    fn cuStreamWaitEvent(stream: CuStream, event: CuEvent, flags: c_uint) -> CuResult;
    fn cuLaunchHostFunc(
        stream: CuStream,
        callback: Option<unsafe extern "C" fn(*mut c_void)>,
        user_data: *mut c_void,
    ) -> CuResult;

    fn cuEventCreate(event: *mut CuEvent, flags: c_uint) -> CuResult;
    fn cuEventDestroy_v2(event: CuEvent) -> CuResult;
    fn cuEventRecord(event: CuEvent, stream: CuStream) -> CuResult;
    fn cuEventSynchronize(event: CuEvent) -> CuResult;
    fn cuEventQuery(event: CuEvent) -> CuResult;
    fn cuEventElapsedTime(milliseconds: *mut f32, start: CuEvent, end: CuEvent) -> CuResult;

    fn cuStreamBeginCapture(stream: CuStream, mode: c_int) -> CuResult;
    fn cuStreamEndCapture(stream: CuStream, graph: *mut CuGraph) -> CuResult;
    fn cuGraphInstantiateWithFlags(
        executable: *mut CuGraphExec,
        graph: CuGraph,
        flags: u64,
    ) -> CuResult;
    fn cuGraphDestroy(graph: CuGraph) -> CuResult;
    fn cuGraphExecDestroy(executable: CuGraphExec) -> CuResult;
    fn cuGraphLaunch(executable: CuGraphExec, stream: CuStream) -> CuResult;
    fn cuGraphUpload(executable: CuGraphExec, stream: CuStream) -> CuResult;
}

#[derive(Debug, Snafu)]
#[snafu(display("CUDA Driver API `{operation}` failed with {name} ({code}): {message}"))]
pub struct CudaError {
    operation: &'static str,
    code: CuResult,
    name: String,
    message: String,
}

pub type CudaResult<T> = std::result::Result<T, CudaError>;

/// Device-supported CUDA stream priorities.
///
/// CUDA uses lower numeric values for higher urgency. These semantic accessors
/// hide that ABI detail from stream owners.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CudaStreamPriorityRange {
    lowest_urgency: c_int,
    highest_urgency: c_int,
}

impl CudaStreamPriorityRange {
    pub const fn lowest_urgency(self) -> c_int {
        self.lowest_urgency
    }

    pub const fn highest_urgency(self) -> c_int {
        self.highest_urgency
    }
}

impl From<CudaError> for ferrule_common::Error {
    fn from(source: CudaError) -> Self {
        Self::Backend {
            source: Box::new(source),
        }
    }
}

impl CudaError {
    fn from_code(operation: &'static str, code: CuResult) -> Self {
        let name = driver_text(code, true).unwrap_or_else(|| "CUDA_ERROR_UNKNOWN".into());
        let message = driver_text(code, false).unwrap_or_else(|| "unknown driver error".into());
        Self {
            operation,
            code,
            name,
            message,
        }
    }
}

fn driver_text(code: CuResult, name: bool) -> Option<String> {
    let mut ptr = std::ptr::null();
    let result = unsafe {
        if name {
            cuGetErrorName(code, &mut ptr)
        } else {
            cuGetErrorString(code, &mut ptr)
        }
    };
    if result != CUDA_SUCCESS || ptr.is_null() {
        None
    } else {
        Some(
            unsafe { CStr::from_ptr(ptr) }
                .to_string_lossy()
                .into_owned(),
        )
    }
}

#[inline]
fn check(operation: &'static str, code: CuResult) -> CudaResult<()> {
    if code == CUDA_SUCCESS {
        Ok(())
    } else {
        Err(CudaError::from_code(operation, code))
    }
}

/// Plain values whose object representation may be copied to CUDA memory.
pub unsafe trait DeviceCopy: Copy + Default + Send + Sync + 'static {}

macro_rules! device_copy {
    ($($ty:ty),+ $(,)?) => {$(unsafe impl DeviceCopy for $ty {})+};
}
device_copy!(u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64);

#[derive(Clone, Copy, Debug)]
pub struct LaunchConfig {
    pub grid_dim: (u32, u32, u32),
    pub block_dim: (u32, u32, u32),
    pub shared_mem_bytes: u32,
}

impl LaunchConfig {
    pub fn for_num_elems(elements: u32) -> Self {
        const BLOCK: u32 = 256;
        Self {
            grid_dim: (elements.div_ceil(BLOCK), 1, 1),
            block_dim: (BLOCK, 1, 1),
            shared_mem_bytes: 0,
        }
    }
}

#[derive(Debug)]
pub struct CudaContext {
    device: CuDevice,
    context: CuContext,
    ordinal: usize,
}

unsafe impl Send for CudaContext {}
unsafe impl Sync for CudaContext {}

impl CudaContext {
    pub fn new(ordinal: usize) -> CudaResult<Arc<Self>> {
        check("cuInit", unsafe { cuInit(0) })?;
        let ordinal_i32 = c_int::try_from(ordinal)
            .map_err(|_| CudaError::from_code("device ordinal conversion", 1))?;
        let mut device = 0;
        check("cuDeviceGet", unsafe {
            cuDeviceGet(&mut device, ordinal_i32)
        })?;
        let mut context = std::ptr::null_mut();
        check("cuDevicePrimaryCtxRetain", unsafe {
            cuDevicePrimaryCtxRetain(&mut context, device)
        })?;
        let this = Arc::new(Self {
            device,
            context,
            ordinal,
        });
        this.bind_to_thread()?;
        Ok(this)
    }

    pub fn ordinal(&self) -> usize {
        self.ordinal
    }

    pub fn bind_to_thread(&self) -> CudaResult<()> {
        let mut current = std::ptr::null_mut();
        check("cuCtxGetCurrent", unsafe { cuCtxGetCurrent(&mut current) })?;
        if current != self.context {
            check("cuCtxSetCurrent", unsafe { cuCtxSetCurrent(self.context) })?;
        }
        Ok(())
    }

    pub fn device_name(&self) -> CudaResult<String> {
        self.bind_to_thread()?;
        let mut bytes = [0 as c_char; 256];
        check("cuDeviceGetName", unsafe {
            cuDeviceGetName(bytes.as_mut_ptr(), bytes.len() as c_int, self.device)
        })?;
        Ok(unsafe { CStr::from_ptr(bytes.as_ptr()) }
            .to_string_lossy()
            .into_owned())
    }

    pub fn memory_info(&self) -> CudaResult<(usize, usize)> {
        self.bind_to_thread()?;
        let (mut free, mut total) = (0, 0);
        check("cuMemGetInfo", unsafe {
            cuMemGetInfo_v2(&mut free, &mut total)
        })?;
        Ok((free, total))
    }

    pub fn stream_priority_range(&self) -> CudaResult<CudaStreamPriorityRange> {
        self.bind_to_thread()?;
        let (mut lowest_urgency, mut highest_urgency) = (0, 0);
        check("cuCtxGetStreamPriorityRange", unsafe {
            cuCtxGetStreamPriorityRange(&mut lowest_urgency, &mut highest_urgency)
        })?;
        Ok(CudaStreamPriorityRange {
            lowest_urgency,
            highest_urgency,
        })
    }

    pub fn default_stream(self: &Arc<Self>) -> Arc<CudaStream> {
        Arc::new(CudaStream {
            raw: std::ptr::null_mut(),
            context: Arc::clone(self),
            owned: false,
        })
    }

    pub fn new_stream(self: &Arc<Self>) -> CudaResult<Arc<CudaStream>> {
        self.bind_to_thread()?;
        let mut raw = std::ptr::null_mut();
        check("cuStreamCreate", unsafe {
            cuStreamCreate(&mut raw, CU_STREAM_NON_BLOCKING)
        })?;
        Ok(Arc::new(CudaStream {
            raw,
            context: Arc::clone(self),
            owned: true,
        }))
    }

    pub fn new_stream_with_priority(
        self: &Arc<Self>,
        priority: c_int,
    ) -> CudaResult<Arc<CudaStream>> {
        self.bind_to_thread()?;
        let mut raw = std::ptr::null_mut();
        check("cuStreamCreateWithPriority", unsafe {
            cuStreamCreateWithPriority(&mut raw, CU_STREAM_NON_BLOCKING, priority)
        })?;
        Ok(Arc::new(CudaStream {
            raw,
            context: Arc::clone(self),
            owned: true,
        }))
    }

    pub fn new_event(self: &Arc<Self>, timing: bool) -> CudaResult<CudaEvent> {
        self.bind_to_thread()?;
        let mut raw = std::ptr::null_mut();
        let flags = if timing {
            CU_EVENT_DEFAULT
        } else {
            CU_EVENT_DISABLE_TIMING
        };
        check("cuEventCreate", unsafe { cuEventCreate(&mut raw, flags) })?;
        Ok(CudaEvent {
            raw,
            context: Arc::clone(self),
        })
    }

    pub(crate) fn device(&self) -> CuDevice {
        self.device
    }
}

impl Drop for CudaContext {
    fn drop(&mut self) {
        let _ = self.bind_to_thread();
        let _ = check("cuDevicePrimaryCtxRelease", unsafe {
            cu_device_primary_ctx_release(self.device)
        });
    }
}

#[derive(Debug)]
pub struct CudaStream {
    raw: CuStream,
    context: Arc<CudaContext>,
    owned: bool,
}

unsafe impl Send for CudaStream {}
unsafe impl Sync for CudaStream {}

impl CudaStream {
    pub fn cu_stream(&self) -> CuStream {
        self.raw
    }

    pub fn context(&self) -> &Arc<CudaContext> {
        &self.context
    }

    pub fn synchronize(&self) -> CudaResult<()> {
        self.context.bind_to_thread()?;
        check("cuStreamSynchronize", unsafe {
            cuStreamSynchronize(self.raw)
        })
    }

    pub fn fork(&self) -> CudaResult<Arc<Self>> {
        let stream = self.context.new_stream()?;
        stream.join(self)?;
        Ok(stream)
    }

    pub fn fork_with_priority(&self, priority: c_int) -> CudaResult<Arc<Self>> {
        let stream = self.context.new_stream_with_priority(priority)?;
        stream.join(self)?;
        Ok(stream)
    }

    pub fn priority(&self) -> CudaResult<c_int> {
        self.context.bind_to_thread()?;
        let mut priority = 0;
        check("cuStreamGetPriority", unsafe {
            cuStreamGetPriority(self.raw, &mut priority)
        })?;
        Ok(priority)
    }

    pub fn join(&self, other: &Self) -> CudaResult<()> {
        self.wait(&other.record_event(None)?)
    }

    pub fn record_event(&self, timing: Option<bool>) -> CudaResult<CudaEvent> {
        let event = self.context.new_event(timing.unwrap_or(false))?;
        event.record(self)?;
        Ok(event)
    }

    pub fn wait(&self, event: &CudaEvent) -> CudaResult<()> {
        self.context.bind_to_thread()?;
        check("cuStreamWaitEvent", unsafe {
            cuStreamWaitEvent(self.raw, event.raw, 0)
        })
    }

    pub fn launch_host_function<F>(&self, callback: F) -> CudaResult<()>
    where
        F: FnOnce() + Send + 'static,
    {
        unsafe extern "C" fn trampoline<F: FnOnce() + Send + 'static>(data: *mut c_void) {
            let callback = unsafe { Box::from_raw(data.cast::<F>()) };
            let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(callback));
        }
        let callback = Box::new(callback);
        let data = Box::into_raw(callback).cast::<c_void>();
        let result = check("cuLaunchHostFunc", unsafe {
            cuLaunchHostFunc(self.raw, Some(trampoline::<F>), data)
        });
        if result.is_err() {
            unsafe { drop(Box::from_raw(data.cast::<F>())) };
        }
        result
    }

    pub(crate) fn begin_capture(&self) -> CudaResult<()> {
        self.context.bind_to_thread()?;
        check("cuStreamBeginCapture", unsafe {
            cuStreamBeginCapture(self.raw, CU_STREAM_CAPTURE_MODE_RELAXED)
        })
    }

    pub(crate) fn end_capture(&self) -> CudaResult<CudaGraph> {
        let mut raw = std::ptr::null_mut();
        check("cuStreamEndCapture", unsafe {
            cuStreamEndCapture(self.raw, &mut raw)
        })?;
        Ok(CudaGraph { raw })
    }
}

impl Drop for CudaStream {
    fn drop(&mut self) {
        if self.owned && !self.raw.is_null() {
            let _ = self.context.bind_to_thread();
            let _ = check("cuStreamDestroy", unsafe { cuStreamDestroy_v2(self.raw) });
        }
    }
}

#[derive(Debug)]
pub struct CudaEvent {
    raw: CuEvent,
    context: Arc<CudaContext>,
}

unsafe impl Send for CudaEvent {}
unsafe impl Sync for CudaEvent {}

impl CudaEvent {
    pub fn record(&self, stream: &CudaStream) -> CudaResult<()> {
        self.context.bind_to_thread()?;
        check("cuEventRecord", unsafe {
            cuEventRecord(self.raw, stream.raw)
        })
    }

    pub fn synchronize(&self) -> CudaResult<()> {
        self.context.bind_to_thread()?;
        check("cuEventSynchronize", unsafe {
            cuEventSynchronize(self.raw)
        })
    }

    pub fn query(&self) -> CudaResult<bool> {
        self.context.bind_to_thread()?;
        match unsafe { cuEventQuery(self.raw) } {
            CUDA_SUCCESS => Ok(true),
            CUDA_ERROR_NOT_READY => Ok(false),
            code => Err(CudaError::from_code("cuEventQuery", code)),
        }
    }

    pub fn elapsed(&self, end: &Self) -> CudaResult<f32> {
        let mut milliseconds = 0.0;
        check("cuEventElapsedTime", unsafe {
            cuEventElapsedTime(&mut milliseconds, self.raw, end.raw)
        })?;
        Ok(milliseconds)
    }
}

impl Drop for CudaEvent {
    fn drop(&mut self) {
        let _ = self.context.bind_to_thread();
        let _ = check("cuEventDestroy", unsafe { cuEventDestroy_v2(self.raw) });
    }
}

struct DeviceAllocation {
    ptr: DevicePtr,
    bytes: usize,
    context: Arc<CudaContext>,
}

impl Drop for DeviceAllocation {
    fn drop(&mut self) {
        if self.ptr != 0 {
            let _ = self.context.bind_to_thread();
            let _ = check("cuMemFree", unsafe { cuMemFree_v2(self.ptr) });
        }
    }
}

unsafe impl Send for DeviceAllocation {}
unsafe impl Sync for DeviceAllocation {}

/// A checked view into a shared CUDA allocation.
///
/// Root buffers and disjoint slices share one allocation owner, so large weight
/// arenas can expose ordinary typed kernel arguments without creating one CUDA
/// allocation per tensor.
pub struct DeviceBuffer<T: DeviceCopy> {
    ptr: DevicePtr,
    len: usize,
    allocation: Arc<DeviceAllocation>,
    _element: PhantomData<T>,
}

unsafe impl<T: DeviceCopy> Send for DeviceBuffer<T> {}
unsafe impl<T: DeviceCopy> Sync for DeviceBuffer<T> {}

impl<T: DeviceCopy> fmt::Debug for DeviceBuffer<T> {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("DeviceBuffer")
            .field("ptr", &format_args!("{:#x}", self.ptr))
            .field("len", &self.len)
            .field("allocation_bytes", &self.allocation.bytes)
            .finish_non_exhaustive()
    }
}

impl<T: DeviceCopy> DeviceBuffer<T> {
    pub fn from_host(stream: &CudaStream, values: &[T]) -> CudaResult<Self> {
        let buffer = unsafe { Self::uninitialized_async(stream, values.len())? };
        buffer.copy_from_host(stream, values)?;
        stream.synchronize()?;
        Ok(buffer)
    }

    pub unsafe fn from_pinned_host(
        stream: &CudaStream,
        values: &PinnedHostBuffer<T>,
    ) -> CudaResult<Self> {
        let buffer = unsafe { Self::uninitialized_async(stream, values.len())? };
        unsafe { buffer.copy_from_pinned_host_async(stream, values)? };
        Ok(buffer)
    }

    pub fn zeroed(stream: &CudaStream, len: usize) -> CudaResult<Self> {
        let buffer = unsafe { Self::uninitialized_async(stream, len)? };
        if buffer.num_bytes() != 0 {
            check("cuMemsetD8Async", unsafe {
                cuMemsetD8Async(buffer.ptr, 0, buffer.num_bytes(), stream.raw)
            })?;
        }
        Ok(buffer)
    }

    pub unsafe fn uninitialized_async(stream: &CudaStream, len: usize) -> CudaResult<Self> {
        let bytes = allocation_bytes::<T>(len)?;
        stream.context.bind_to_thread()?;
        let mut ptr = 0;
        if bytes != 0 {
            check("cuMemAlloc", unsafe { cuMemAlloc_v2(&mut ptr, bytes) })?;
        }
        Ok(Self {
            ptr,
            len,
            allocation: Arc::new(DeviceAllocation {
                ptr,
                bytes,
                context: Arc::clone(&stream.context),
            }),
            _element: PhantomData,
        })
    }

    pub unsafe fn managed(context: &Arc<CudaContext>, len: usize) -> CudaResult<Self> {
        let bytes = allocation_bytes::<T>(len)?;
        context.bind_to_thread()?;
        let mut ptr = 0;
        if bytes != 0 {
            check("cuMemAllocManaged", unsafe {
                cuMemAllocManaged(&mut ptr, bytes, CU_MEM_ATTACH_GLOBAL)
            })?;
            check("cuMemAdvise", unsafe {
                cuMemAdvise(ptr, bytes, CU_MEM_ADVISE_SET_READ_MOSTLY, context.device())
            })?;
        }
        Ok(Self {
            ptr,
            len,
            allocation: Arc::new(DeviceAllocation {
                ptr,
                bytes,
                context: Arc::clone(context),
            }),
            _element: PhantomData,
        })
    }

    pub unsafe fn from_raw_parts(ptr: DevicePtr, len: usize, context: Arc<CudaContext>) -> Self {
        Self {
            ptr,
            len,
            allocation: Arc::new(DeviceAllocation {
                ptr,
                bytes: len.saturating_mul(std::mem::size_of::<T>()),
                context,
            }),
            _element: PhantomData,
        }
    }

    pub fn slice(&self, offset: usize, len: usize) -> CudaResult<Self> {
        let end = offset
            .checked_add(len)
            .ok_or_else(|| CudaError::from_code("device buffer slice overflow", 1))?;
        if end > self.len {
            return Err(CudaError::from_code("device buffer slice out of bounds", 1));
        }
        let byte_offset = offset
            .checked_mul(std::mem::size_of::<T>())
            .ok_or_else(|| CudaError::from_code("device buffer byte offset overflow", 1))?;
        let ptr = self
            .ptr
            .checked_add(byte_offset as u64)
            .ok_or_else(|| CudaError::from_code("device buffer pointer overflow", 1))?;
        Ok(Self {
            ptr,
            len,
            allocation: Arc::clone(&self.allocation),
            _element: PhantomData,
        })
    }

    pub fn cu_deviceptr(&self) -> DevicePtr {
        self.ptr
    }

    pub fn len(&self) -> usize {
        self.len
    }

    pub fn is_empty(&self) -> bool {
        self.len == 0
    }

    pub fn num_bytes(&self) -> usize {
        self.len.saturating_mul(std::mem::size_of::<T>())
    }

    pub fn context(&self) -> &Arc<CudaContext> {
        &self.allocation.context
    }

    pub fn copy_from_host(&self, stream: &CudaStream, values: &[T]) -> CudaResult<()> {
        if values.len() != self.len {
            return Err(CudaError::from_code("host-to-device length mismatch", 1));
        }
        if self.num_bytes() == 0 {
            return Ok(());
        }
        check("cuMemcpyHtoDAsync", unsafe {
            cuMemcpyHtoDAsync_v2(
                self.ptr,
                values.as_ptr().cast(),
                self.num_bytes(),
                stream.raw,
            )
        })
    }

    pub unsafe fn copy_from_pinned_host_async(
        &self,
        stream: &CudaStream,
        values: &PinnedHostBuffer<T>,
    ) -> CudaResult<()> {
        if values.len() != self.len {
            return Err(CudaError::from_code(
                "pinned host-to-device length mismatch",
                1,
            ));
        }
        if self.num_bytes() == 0 {
            return Ok(());
        }
        check("cuMemcpyHtoDAsync", unsafe {
            cuMemcpyHtoDAsync_v2(
                self.ptr,
                values.as_ptr().cast(),
                self.num_bytes(),
                stream.raw,
            )
        })
    }

    pub fn to_host_vec(&self, stream: &CudaStream) -> CudaResult<Vec<T>> {
        let mut values = vec![T::default(); self.len];
        self.copy_to_host(stream, &mut values)?;
        Ok(values)
    }

    pub fn copy_to_host(&self, stream: &CudaStream, values: &mut [T]) -> CudaResult<()> {
        if values.len() != self.len {
            return Err(CudaError::from_code("device-to-host length mismatch", 1));
        }
        if self.num_bytes() != 0 {
            check("cuMemcpyDtoHAsync", unsafe {
                cuMemcpyDtoHAsync_v2(
                    values.as_mut_ptr().cast(),
                    self.ptr,
                    self.num_bytes(),
                    stream.raw,
                )
            })?;
        }
        stream.synchronize()
    }

    pub unsafe fn copy_to_pinned_host_async(
        &self,
        stream: &CudaStream,
        values: &mut PinnedHostBuffer<T>,
    ) -> CudaResult<()> {
        if values.len() != self.len {
            return Err(CudaError::from_code(
                "device-to-pinned-host length mismatch",
                1,
            ));
        }
        if self.num_bytes() == 0 {
            return Ok(());
        }
        check("cuMemcpyDtoHAsync", unsafe {
            cuMemcpyDtoHAsync_v2(
                values.as_mut_ptr().cast(),
                self.ptr,
                self.num_bytes(),
                stream.raw,
            )
        })
    }
}

pub struct PinnedHostBuffer<T: DeviceCopy> {
    ptr: NonNull<T>,
    len: usize,
    bytes: usize,
    context: Arc<CudaContext>,
}

unsafe impl<T: DeviceCopy> Send for PinnedHostBuffer<T> {}
unsafe impl<T: DeviceCopy> Sync for PinnedHostBuffer<T> {}

impl<T: DeviceCopy> fmt::Debug for PinnedHostBuffer<T> {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("PinnedHostBuffer")
            .field("ptr", &self.ptr)
            .field("len", &self.len)
            .finish_non_exhaustive()
    }
}

impl<T: DeviceCopy> PinnedHostBuffer<T> {
    pub fn zeroed(context: &Arc<CudaContext>, len: usize) -> CudaResult<Self> {
        let buffer = Self::allocate(context, len)?;
        if buffer.bytes != 0 {
            unsafe { std::ptr::write_bytes(buffer.ptr.as_ptr().cast::<u8>(), 0, buffer.bytes) };
        }
        Ok(buffer)
    }

    pub fn from_slice(context: &Arc<CudaContext>, values: &[T]) -> CudaResult<Self> {
        let mut buffer = Self::allocate(context, values.len())?;
        if !values.is_empty() {
            buffer.as_mut_slice().copy_from_slice(values);
        }
        Ok(buffer)
    }

    fn allocate(context: &Arc<CudaContext>, len: usize) -> CudaResult<Self> {
        let bytes = allocation_bytes::<T>(len)?;
        context.bind_to_thread()?;
        let ptr = if bytes == 0 {
            NonNull::dangling()
        } else {
            let mut ptr = std::ptr::null_mut();
            check("cuMemAllocHost", unsafe {
                cuMemAllocHost_v2(&mut ptr, bytes)
            })?;
            NonNull::new(ptr.cast::<T>())
                .ok_or_else(|| CudaError::from_code("cuMemAllocHost null pointer", 1))?
        };
        Ok(Self {
            ptr,
            len,
            bytes,
            context: Arc::clone(context),
        })
    }

    pub fn len(&self) -> usize {
        self.len
    }

    pub fn is_empty(&self) -> bool {
        self.len == 0
    }

    pub fn as_ptr(&self) -> *const T {
        self.ptr.as_ptr()
    }

    pub fn as_mut_ptr(&mut self) -> *mut T {
        self.ptr.as_ptr()
    }

    pub fn as_slice(&self) -> &[T] {
        unsafe { std::slice::from_raw_parts(self.ptr.as_ptr(), self.len) }
    }

    pub fn as_mut_slice(&mut self) -> &mut [T] {
        unsafe { std::slice::from_raw_parts_mut(self.ptr.as_ptr(), self.len) }
    }

    pub fn context(&self) -> &Arc<CudaContext> {
        &self.context
    }

    pub fn device_pointer(&self) -> CudaResult<DevicePtr> {
        let mut ptr = 0;
        check("cuMemHostGetDevicePointer", unsafe {
            cuMemHostGetDevicePointer_v2(&mut ptr, self.ptr.as_ptr().cast(), 0)
        })?;
        Ok(ptr)
    }
}

impl<T: DeviceCopy> Deref for PinnedHostBuffer<T> {
    type Target = [T];

    fn deref(&self) -> &Self::Target {
        self.as_slice()
    }
}

impl<T: DeviceCopy> DerefMut for PinnedHostBuffer<T> {
    fn deref_mut(&mut self) -> &mut Self::Target {
        self.as_mut_slice()
    }
}

impl<T: DeviceCopy> Drop for PinnedHostBuffer<T> {
    fn drop(&mut self) {
        if self.bytes != 0 {
            let _ = self.context.bind_to_thread();
            let _ = check("cuMemFreeHost", unsafe {
                cuMemFreeHost(self.ptr.as_ptr().cast())
            });
        }
    }
}

pub(crate) struct CudaGraph {
    raw: CuGraph,
}

impl CudaGraph {
    pub(crate) fn instantiate(&self) -> CudaResult<CudaGraphExec> {
        let mut raw = std::ptr::null_mut();
        check("cuGraphInstantiate", unsafe {
            cuGraphInstantiateWithFlags(&mut raw, self.raw, 0)
        })?;
        Ok(CudaGraphExec { raw })
    }
}

impl Drop for CudaGraph {
    fn drop(&mut self) {
        if !self.raw.is_null() {
            let _ = check("cuGraphDestroy", unsafe { cuGraphDestroy(self.raw) });
        }
    }
}

pub(crate) struct CudaGraphExec {
    raw: CuGraphExec,
}

impl CudaGraphExec {
    pub(crate) fn launch(&self, stream: &CudaStream) -> CudaResult<()> {
        check("cuGraphLaunch", unsafe {
            cuGraphLaunch(self.raw, stream.raw)
        })
    }

    pub(crate) fn upload(&self, stream: &CudaStream) -> CudaResult<()> {
        check("cuGraphUpload", unsafe {
            cuGraphUpload(self.raw, stream.raw)
        })
    }
}

impl Drop for CudaGraphExec {
    fn drop(&mut self) {
        if !self.raw.is_null() {
            let _ = check("cuGraphExecDestroy", unsafe {
                cuGraphExecDestroy(self.raw)
            });
        }
    }
}

pub(crate) fn copy_device_to_device(
    stream: &CudaStream,
    destination: DevicePtr,
    source: DevicePtr,
    bytes: usize,
) -> CudaResult<()> {
    if bytes == 0 {
        return Ok(());
    }
    check("cuMemcpyDtoDAsync", unsafe {
        cuMemcpyDtoDAsync_v2(destination, source, bytes, stream.raw)
    })
}

pub(crate) fn copy_host_to_device(
    stream: &CudaStream,
    destination: DevicePtr,
    source: *const c_void,
    bytes: usize,
) -> CudaResult<()> {
    if bytes == 0 {
        return Ok(());
    }
    check("cuMemcpyHtoDAsync", unsafe {
        cuMemcpyHtoDAsync_v2(destination, source, bytes, stream.raw)
    })
}

pub(crate) fn copy_device_to_host(
    stream: &CudaStream,
    destination: *mut c_void,
    source: DevicePtr,
    bytes: usize,
) -> CudaResult<()> {
    if bytes == 0 {
        return Ok(());
    }
    check("cuMemcpyDtoHAsync", unsafe {
        cuMemcpyDtoHAsync_v2(destination, source, bytes, stream.raw)
    })
}

pub(crate) fn memset_u32(
    stream: &CudaStream,
    destination: DevicePtr,
    value: u32,
    elements: usize,
) -> CudaResult<()> {
    if elements == 0 {
        return Ok(());
    }
    check("cuMemsetD32Async", unsafe {
        cuMemsetD32Async(destination, value, elements, stream.raw)
    })
}

pub(crate) fn alloc_host(bytes: usize) -> CudaResult<*mut c_void> {
    let mut ptr = std::ptr::null_mut();
    if bytes != 0 {
        check("cuMemAllocHost", unsafe {
            cuMemAllocHost_v2(&mut ptr, bytes)
        })?;
    }
    Ok(ptr)
}

pub(crate) fn free_host(ptr: *mut c_void) -> CudaResult<()> {
    if ptr.is_null() {
        Ok(())
    } else {
        check("cuMemFreeHost", unsafe { cuMemFreeHost(ptr) })
    }
}

pub(crate) fn host_device_pointer(ptr: *mut c_void) -> CudaResult<DevicePtr> {
    let mut device = 0;
    check("cuMemHostGetDevicePointer", unsafe {
        cuMemHostGetDevicePointer_v2(&mut device, ptr, 0)
    })?;
    Ok(device)
}

fn allocation_bytes<T>(len: usize) -> CudaResult<usize> {
    len.checked_mul(std::mem::size_of::<T>())
        .ok_or_else(|| CudaError::from_code("CUDA allocation size overflow", 1))
}
