//! Minimal CUDA Driver API ownership layer used by Ferrule.
//!
//! This module deliberately exposes only the context, stream, event, graph and
//! memory operations required by the backend. Kernel contracts live in the
//! native operator catalog instead of being generated by a Rust device-code
//! framework.

use std::ffi::{CStr, c_char, c_int, c_uint, c_void};
use std::fmt;
use std::marker::PhantomData;

use std::ops::{Deref, DerefMut};
use std::ptr::NonNull;
use std::sync::{Arc, Mutex, MutexGuard, Weak};

use super::allocator::{CudaAllocatorMetrics, CudaDeviceAllocator, CudaDeviceBlock};

use snafu::Snafu;

pub type DevicePtr = u64;
type CuDevice = c_int;
type CuContext = *mut c_void;
type CuStream = *mut c_void;
type CuEvent = *mut c_void;
type CuGraph = *mut c_void;
type CuGraphExec = *mut c_void;
type CuResult = c_int;

const CUDA_SUCCESS: CuResult = 0;
const CUDA_ERROR_NOT_READY: CuResult = 600;
const CU_STREAM_NON_BLOCKING: c_uint = 1;
const CU_EVENT_DEFAULT: c_uint = 0;
const CU_EVENT_DISABLE_TIMING: c_uint = 2;
const CU_STREAM_CAPTURE_MODE_RELAXED: c_int = 2;
const CU_MEM_ATTACH_GLOBAL: c_uint = 1;
const CU_MEM_ADVISE_SET_READ_MOSTLY: c_int = 1;

#[link(name = "cuda")]
unsafe extern "C" {
    fn cuInit(flags: c_uint) -> CuResult;
    fn cuGetErrorName(error: CuResult, name: *mut *const c_char) -> CuResult;
    fn cuGetErrorString(error: CuResult, description: *mut *const c_char) -> CuResult;
    fn cuDeviceGet(device: *mut CuDevice, ordinal: c_int) -> CuResult;
    fn cuDeviceGetCount(count: *mut c_int) -> CuResult;
    fn cuDeviceGetName(name: *mut c_char, len: c_int, device: CuDevice) -> CuResult;
    fn cuDevicePrimaryCtxRetain(context: *mut CuContext, device: CuDevice) -> CuResult;
    #[link_name = "cuDevicePrimaryCtxRelease_v2"]
    fn cu_device_primary_ctx_release(device: CuDevice) -> CuResult;
    fn cuCtxGetCurrent(context: *mut CuContext) -> CuResult;
    fn cuCtxSetCurrent(context: CuContext) -> CuResult;
    fn cuCtxSynchronize() -> CuResult;
    fn cuCtxGetStreamPriorityRange(
        least_priority: *mut c_int,
        greatest_priority: *mut c_int,
    ) -> CuResult;

    fn cuMemGetInfo_v2(free: *mut usize, total: *mut usize) -> CuResult;
    fn cuMemAlloc_v2(ptr: *mut DevicePtr, bytes: usize) -> CuResult;
    fn cuMemAllocManaged(ptr: *mut DevicePtr, bytes: usize, flags: c_uint) -> CuResult;
    fn cuMemFree_v2(ptr: DevicePtr) -> CuResult;
    fn cuMemAllocHost_v2(ptr: *mut *mut c_void, bytes: usize) -> CuResult;
    fn cuMemFreeHost(ptr: *mut c_void) -> CuResult;
    fn cuMemHostGetDevicePointer_v2(
        device_ptr: *mut DevicePtr,
        host_ptr: *mut c_void,
        flags: c_uint,
    ) -> CuResult;
    fn cuMemAdvise(ptr: DevicePtr, bytes: usize, advice: c_int, device: CuDevice) -> CuResult;
    fn cuMemcpyHtoDAsync_v2(
        dst: DevicePtr,
        src: *const c_void,
        bytes: usize,
        stream: CuStream,
    ) -> CuResult;
    fn cuMemcpyDtoHAsync_v2(
        dst: *mut c_void,
        src: DevicePtr,
        bytes: usize,
        stream: CuStream,
    ) -> CuResult;
    fn cuMemcpyDtoDAsync_v2(
        dst: DevicePtr,
        src: DevicePtr,
        bytes: usize,
        stream: CuStream,
    ) -> CuResult;
    fn cuMemsetD8Async(dst: DevicePtr, value: u8, count: usize, stream: CuStream) -> CuResult;
    fn cuMemsetD32Async(dst: DevicePtr, value: u32, count: usize, stream: CuStream) -> CuResult;

    fn cuStreamCreate(stream: *mut CuStream, flags: c_uint) -> CuResult;
    fn cuStreamCreateWithPriority(
        stream: *mut CuStream,
        flags: c_uint,
        priority: c_int,
    ) -> CuResult;
    fn cuStreamGetPriority(stream: CuStream, priority: *mut c_int) -> CuResult;
    fn cuStreamDestroy_v2(stream: CuStream) -> CuResult;
    fn cuStreamSynchronize(stream: CuStream) -> CuResult;
    fn cuStreamWaitEvent(stream: CuStream, event: CuEvent, flags: c_uint) -> CuResult;
    fn cuLaunchHostFunc(
        stream: CuStream,
        callback: Option<unsafe extern "C" fn(*mut c_void)>,
        user_data: *mut c_void,
    ) -> CuResult;

    fn cuEventCreate(event: *mut CuEvent, flags: c_uint) -> CuResult;
    fn cuEventDestroy_v2(event: CuEvent) -> CuResult;
    fn cuEventRecord(event: CuEvent, stream: CuStream) -> CuResult;
    fn cuEventSynchronize(event: CuEvent) -> CuResult;
    fn cuEventQuery(event: CuEvent) -> CuResult;
    fn cuEventElapsedTime(milliseconds: *mut f32, start: CuEvent, end: CuEvent) -> CuResult;

    fn cuStreamBeginCapture(stream: CuStream, mode: c_int) -> CuResult;
    fn cuStreamEndCapture(stream: CuStream, graph: *mut CuGraph) -> CuResult;
    fn cuGraphInstantiateWithFlags(
        executable: *mut CuGraphExec,
        graph: CuGraph,
        flags: u64,
    ) -> CuResult;
    fn cuGraphDestroy(graph: CuGraph) -> CuResult;
    fn cuGraphExecDestroy(executable: CuGraphExec) -> CuResult;
    fn cuGraphLaunch(executable: CuGraphExec, stream: CuStream) -> CuResult;
    fn cuGraphUpload(executable: CuGraphExec, stream: CuStream) -> CuResult;
}

#[derive(Debug, Snafu)]
#[snafu(display("CUDA Driver API `{operation}` failed with {name} ({code}): {message}"))]
pub struct CudaError {
    operation: &'static str,
    code: CuResult,
    name: String,
    message: String,
}

pub type CudaResult<T> = std::result::Result<T, CudaError>;

/// Device-supported CUDA stream priorities.
///
/// CUDA uses lower numeric values for higher urgency. These semantic accessors
/// hide that ABI detail from stream owners.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CudaStreamPriorityRange {
    lowest_urgency: c_int,
    highest_urgency: c_int,
}

impl CudaStreamPriorityRange {
    pub const fn lowest_urgency(self) -> c_int {
        self.lowest_urgency
    }

    pub const fn highest_urgency(self) -> c_int {
        self.highest_urgency
    }
}

impl From<CudaError> for ferrule_common::Error {
    fn from(source: CudaError) -> Self {
        Self::Backend {
            source: Box::new(source),
        }
    }
}

impl CudaError {
    pub(crate) fn internal(message: impl Into<String>) -> Self {
        Self {
            operation: "CUDA device allocator",
            code: 1,
            name: "CUDA_ERROR_INVALID_VALUE".into(),
            message: message.into(),
        }
    }

    fn from_code(operation: &'static str, code: CuResult) -> Self {
        let name = driver_text(code, true).unwrap_or_else(|| "CUDA_ERROR_UNKNOWN".into());
        let message = driver_text(code, false).unwrap_or_else(|| "unknown driver error".into());
        Self {
            operation,
            code,
            name,
            message,
        }
    }
}

fn driver_text(code: CuResult, name: bool) -> Option<String> {
    let mut ptr = std::ptr::null();
    let result = unsafe {
        if name {
            cuGetErrorName(code, &mut ptr)
        } else {
            cuGetErrorString(code, &mut ptr)
        }
    };
    if result != CUDA_SUCCESS || ptr.is_null() {
        None
    } else {
        Some(
            unsafe { CStr::from_ptr(ptr) }
                .to_string_lossy()
                .into_owned(),
        )
    }
}

#[inline]
fn check(operation: &'static str, code: CuResult) -> CudaResult<()> {
    if code == CUDA_SUCCESS {
        Ok(())
    } else {
        Err(CudaError::from_code(operation, code))
    }
}

/// Plain values whose object representation may be copied to CUDA memory.
///
/// # Safety
/// Implementors must be plain-old-data: no padding-dependent semantics, no
/// interior pointers, and bit patterns that remain valid after a byte copy.
pub unsafe trait DeviceCopy: Copy + Default + Send + Sync + 'static {}

macro_rules! device_copy {
    ($($ty:ty),+ $(,)?) => {$(unsafe impl DeviceCopy for $ty {})+};
}
device_copy!(u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64);

#[derive(Clone, Copy, Debug)]
pub struct LaunchConfig {
    pub grid_dim: (u32, u32, u32),
    pub block_dim: (u32, u32, u32),
    pub shared_mem_bytes: u32,
}

impl LaunchConfig {
    pub fn for_num_elems(elements: u32) -> Self {
        const BLOCK: u32 = 256;
        Self {
            grid_dim: (elements.div_ceil(BLOCK), 1, 1),
            block_dim: (BLOCK, 1, 1),
            shared_mem_bytes: 0,
        }
    }
}

/// Unknown is sticky: neither a local depth decrement nor an unrelated sync
/// proves that capture ended or that graph consumers retired.
#[derive(Debug, Default)]
pub(crate) struct CaptureState {
    depth: usize,
    owner: Option<usize>,
    unknown: bool,
}

impl CaptureState {
    pub(crate) fn blocks_allocation(&self) -> bool {
        self.depth != 0 || self.unknown
    }

    fn end_result(&mut self, code: CuResult, has_graph: bool) {
        // EndCapture terminates an invalidated sequence too (901). All other
        // failures, including context-binding failure, lack termination proof.
        if !self.unknown && ((code == CUDA_SUCCESS && has_graph) || code == 901) {
            self.depth = self.depth.saturating_sub(1);
            self.owner = None;
        } else {
            self.unknown = true;
        }
    }
}

#[cfg(test)]
#[derive(Clone, Copy)]
pub(crate) enum GraphFault {
    Begin = 0,
    End = 1,
    Instantiate = 2,
    Launch = 3,
    Upload = 4,
}

#[cfg(test)]
#[derive(Default)]
struct GraphTestHooks {
    faults: std::sync::atomic::AtomicUsize,
    calls: [std::sync::atomic::AtomicUsize; 5],
}

pub struct CudaContext {
    device: CuDevice,
    context: CuContext,
    ordinal: usize,
    allocator: Arc<CudaDeviceAllocator>,
    streams: Mutex<Vec<Weak<CudaStream>>>,
    capture_depth: Mutex<CaptureState>,
    #[cfg(test)]
    graph_test_hooks: GraphTestHooks,
}

impl fmt::Debug for CudaContext {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("CudaContext")
            .field("device", &self.device)
            .field("ordinal", &self.ordinal)
            .field("allocator", &self.allocator.metrics())
            .finish_non_exhaustive()
    }
}

unsafe impl Send for CudaContext {}
unsafe impl Sync for CudaContext {}

impl CudaContext {
    pub fn device_count() -> CudaResult<usize> {
        check("cuInit", unsafe { cuInit(0) })?;
        let mut count = 0;
        check("cuDeviceGetCount", unsafe { cuDeviceGetCount(&mut count) })?;
        usize::try_from(count).map_err(|_| CudaError::from_code("device count conversion", 1))
    }

    pub fn new(ordinal: usize) -> CudaResult<Arc<Self>> {
        check("cuInit", unsafe { cuInit(0) })?;
        let ordinal_i32 = c_int::try_from(ordinal)
            .map_err(|_| CudaError::from_code("device ordinal conversion", 1))?;
        let mut device = 0;
        check("cuDeviceGet", unsafe {
            cuDeviceGet(&mut device, ordinal_i32)
        })?;
        let mut context = std::ptr::null_mut();
        check("cuDevicePrimaryCtxRetain", unsafe {
            cuDevicePrimaryCtxRetain(&mut context, device)
        })?;
        let this = Arc::new_cyclic(|weak| Self {
            device,
            context,
            ordinal,
            allocator: CudaDeviceAllocator::new(weak.clone()),
            streams: Mutex::new(Vec::new()),
            capture_depth: Mutex::new(CaptureState::default()),
            #[cfg(test)]
            graph_test_hooks: GraphTestHooks::default(),
        });
        this.bind_to_thread()?;
        Ok(this)
    }

    pub fn ordinal(&self) -> usize {
        self.ordinal
    }

    pub fn bind_to_thread(&self) -> CudaResult<()> {
        let mut current = std::ptr::null_mut();
        check("cuCtxGetCurrent", unsafe { cuCtxGetCurrent(&mut current) })?;
        if current != self.context {
            check("cuCtxSetCurrent", unsafe { cuCtxSetCurrent(self.context) })?;
        }
        Ok(())
    }

    pub fn device_name(&self) -> CudaResult<String> {
        self.bind_to_thread()?;
        let mut bytes = [0 as c_char; 256];
        check("cuDeviceGetName", unsafe {
            cuDeviceGetName(bytes.as_mut_ptr(), bytes.len() as c_int, self.device)
        })?;
        Ok(unsafe { CStr::from_ptr(bytes.as_ptr()) }
            .to_string_lossy()
            .into_owned())
    }

    pub fn memory_info(&self) -> CudaResult<(usize, usize)> {
        self.bind_to_thread()?;
        let (mut free, mut total) = (0, 0);
        check("cuMemGetInfo", unsafe {
            cuMemGetInfo_v2(&mut free, &mut total)
        })?;
        Ok((free, total))
    }

    pub fn stream_priority_range(&self) -> CudaResult<CudaStreamPriorityRange> {
        self.bind_to_thread()?;
        let (mut lowest_urgency, mut highest_urgency) = (0, 0);
        check("cuCtxGetStreamPriorityRange", unsafe {
            cuCtxGetStreamPriorityRange(&mut lowest_urgency, &mut highest_urgency)
        })?;
        Ok(CudaStreamPriorityRange {
            lowest_urgency,
            highest_urgency,
        })
    }

    pub fn default_stream(self: &Arc<Self>) -> Arc<CudaStream> {
        let stream = Arc::new(CudaStream {
            raw: std::ptr::null_mut(),
            context: Arc::clone(self),
            owned: false,
        });
        self.register_stream(&stream);
        stream
    }

    pub fn new_stream(self: &Arc<Self>) -> CudaResult<Arc<CudaStream>> {
        self.bind_to_thread()?;
        let mut raw = std::ptr::null_mut();
        check("cuStreamCreate", unsafe {
            cuStreamCreate(&mut raw, CU_STREAM_NON_BLOCKING)
        })?;
        let stream = Arc::new(CudaStream {
            raw,
            context: Arc::clone(self),
            owned: true,
        });
        self.register_stream(&stream);
        Ok(stream)
    }

    pub fn new_stream_with_priority(
        self: &Arc<Self>,
        priority: c_int,
    ) -> CudaResult<Arc<CudaStream>> {
        self.bind_to_thread()?;
        let mut raw = std::ptr::null_mut();
        check("cuStreamCreateWithPriority", unsafe {
            cuStreamCreateWithPriority(&mut raw, CU_STREAM_NON_BLOCKING, priority)
        })?;
        let stream = Arc::new(CudaStream {
            raw,
            context: Arc::clone(self),
            owned: true,
        });
        self.register_stream(&stream);
        Ok(stream)
    }

    fn register_stream(&self, stream: &Arc<CudaStream>) {
        let mut streams = self
            .streams
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        streams.retain(|candidate| candidate.strong_count() != 0);
        streams.push(Arc::downgrade(stream));
    }

    pub(crate) fn record_retirement_events(&self) -> Result<Vec<CudaRetirementEvent>, ()> {
        let streams = self
            .streams
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner)
            .iter()
            .filter_map(Weak::upgrade)
            .collect::<Vec<_>>();
        let mut events = Vec::with_capacity(streams.len());
        for stream in streams {
            self.bind_to_thread().map_err(|_| ())?;
            let mut raw = std::ptr::null_mut();
            check("cuEventCreate", unsafe {
                cuEventCreate(&mut raw, CU_EVENT_DISABLE_TIMING)
            })
            .map_err(|_| ())?;
            if check("cuEventRecord", unsafe { cuEventRecord(raw, stream.raw) }).is_err() {
                let _ = check("cuEventDestroy", unsafe { cuEventDestroy_v2(raw) });
                return Err(());
            }
            events.push(CudaRetirementEvent {
                raw,
                context: self.context,
            });
        }
        Ok(events)
    }

    pub(crate) fn synchronize_registered_streams(&self) -> CudaResult<()> {
        self.check_graph_ready()?;
        self.bind_to_thread()?;
        check("cuCtxSynchronizeAllocatorRetirement", unsafe {
            cuCtxSynchronize()
        })
    }

    pub(crate) fn is_capturing(&self) -> bool {
        self.capture_state().blocks_allocation()
    }

    pub(crate) fn capture_state(&self) -> MutexGuard<'_, CaptureState> {
        self.capture_depth
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner)
    }

    pub(crate) fn graph_completion_unknown(&self) -> bool {
        self.capture_state().unknown
    }

    pub(crate) fn mark_graph_unknown(&self) {
        self.capture_state().unknown = true;
    }

    pub(crate) fn check_graph_ready(&self) -> CudaResult<()> {
        if self.is_capturing() {
            return Err(CudaError::internal(
                "CUDA capture active or graph completion unknown",
            ));
        }
        Ok(())
    }

    #[cfg(test)]
    pub(crate) fn arm_graph_fault(&self, fault: GraphFault) {
        self.graph_test_hooks
            .faults
            .fetch_or(1 << fault as usize, std::sync::atomic::Ordering::SeqCst);
    }

    #[cfg(test)]
    pub(crate) fn graph_calls(&self, fault: GraphFault) -> usize {
        self.graph_test_hooks.calls[fault as usize].load(std::sync::atomic::Ordering::SeqCst)
    }

    #[cfg(test)]
    fn graph_fault(&self, fault: GraphFault) -> bool {
        use std::sync::atomic::Ordering::SeqCst;
        self.graph_test_hooks.calls[fault as usize].fetch_add(1, SeqCst);
        let bit = 1 << fault as usize;
        self.graph_test_hooks.faults.fetch_and(!bit, SeqCst) & bit != 0
    }

    pub(crate) fn allocator_metrics(&self) -> CudaAllocatorMetrics {
        self.allocator.poll_retirements();
        self.allocator.metrics()
    }

    pub(crate) fn trim_allocator(&self) -> CudaResult<usize> {
        self.allocator.trim()
    }

    pub(crate) fn shutdown_allocator(&self) {
        self.allocator.shutdown();
    }

    pub fn new_event(self: &Arc<Self>, timing: bool) -> CudaResult<CudaEvent> {
        self.bind_to_thread()?;
        let mut raw = std::ptr::null_mut();
        let flags = if timing {
            CU_EVENT_DEFAULT
        } else {
            CU_EVENT_DISABLE_TIMING
        };
        check("cuEventCreate", unsafe { cuEventCreate(&mut raw, flags) })?;
        Ok(CudaEvent {
            raw,
            context: Arc::clone(self),
        })
    }

    pub(crate) fn device(&self) -> CuDevice {
        self.device
    }
}

pub(crate) fn driver_alloc(bytes: usize) -> CudaResult<DevicePtr> {
    let mut ptr = 0;
    if bytes != 0 {
        check("cuMemAllocAllocatorSegment", unsafe {
            cuMemAlloc_v2(&mut ptr, bytes)
        })?;
    }
    Ok(ptr)
}

pub(crate) fn driver_free(ptr: DevicePtr) -> CudaResult<()> {
    if ptr == 0 {
        Ok(())
    } else {
        check("cuMemFreeAllocatorSegment", unsafe { cuMemFree_v2(ptr) })
    }
}

impl Drop for CudaContext {
    fn drop(&mut self) {
        if self.graph_completion_unknown() {
            // Do not release a primary-context retain with unknown graph custody.
            return;
        }
        self.allocator.shutdown_with_context(self, true);
        let _ = self.bind_to_thread();
        let _ = check("cuDevicePrimaryCtxRelease", unsafe {
            cu_device_primary_ctx_release(self.device)
        });
    }
}

#[derive(Debug)]
pub struct CudaStream {
    raw: CuStream,
    context: Arc<CudaContext>,
    owned: bool,
}

unsafe impl Send for CudaStream {}
unsafe impl Sync for CudaStream {}

impl CudaStream {
    pub fn cu_stream(&self) -> CuStream {
        self.raw
    }

    pub fn context(&self) -> &Arc<CudaContext> {
        &self.context
    }

    pub fn synchronize(&self) -> CudaResult<()> {
        self.context.check_graph_ready()?;
        self.context.bind_to_thread()?;
        check("cuStreamSynchronize", unsafe {
            cuStreamSynchronize(self.raw)
        })
    }

    pub fn fork(&self) -> CudaResult<Arc<Self>> {
        let stream = self.context.new_stream()?;
        stream.join(self)?;
        Ok(stream)
    }

    pub fn fork_with_priority(&self, priority: c_int) -> CudaResult<Arc<Self>> {
        let stream = self.context.new_stream_with_priority(priority)?;
        stream.join(self)?;
        Ok(stream)
    }

    pub fn priority(&self) -> CudaResult<c_int> {
        self.context.bind_to_thread()?;
        let mut priority = 0;
        check("cuStreamGetPriority", unsafe {
            cuStreamGetPriority(self.raw, &mut priority)
        })?;
        Ok(priority)
    }

    pub fn join(&self, other: &Self) -> CudaResult<()> {
        self.wait(&other.record_event(None)?)
    }

    pub fn record_event(&self, timing: Option<bool>) -> CudaResult<CudaEvent> {
        let event = self.context.new_event(timing.unwrap_or(false))?;
        event.record(self)?;
        Ok(event)
    }

    pub fn wait(&self, event: &CudaEvent) -> CudaResult<()> {
        self.context.bind_to_thread()?;
        check("cuStreamWaitEvent", unsafe {
            cuStreamWaitEvent(self.raw, event.raw, 0)
        })
    }

    pub fn launch_host_function<F>(&self, callback: F) -> CudaResult<()>
    where
        F: FnOnce() + Send + 'static,
    {
        unsafe extern "C" fn trampoline<F: FnOnce() + Send + 'static>(data: *mut c_void) {
            let callback = unsafe { Box::from_raw(data.cast::<F>()) };
            let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(callback));
        }
        let callback = Box::new(callback);
        let data = Box::into_raw(callback).cast::<c_void>();
        let result = check("cuLaunchHostFunc", unsafe {
            cuLaunchHostFunc(self.raw, Some(trampoline::<F>), data)
        });
        if result.is_err() {
            unsafe { drop(Box::from_raw(data.cast::<F>())) };
        }
        result
    }

    pub(crate) fn owner(&self) -> CudaResult<Arc<Self>> {
        self.context
            .streams
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner)
            .iter()
            .filter_map(Weak::upgrade)
            .find(|stream| std::ptr::eq(stream.as_ref(), self))
            .ok_or_else(|| CudaError::internal("CUDA stream owner is unavailable"))
    }

    pub(crate) fn begin_capture(&self) -> CudaResult<()> {
        self.context.bind_to_thread()?;
        let mut state = self.context.capture_state();
        if state.blocks_allocation() {
            return Err(CudaError::internal(
                "CUDA capture active or graph completion unknown",
            ));
        }
        #[cfg(test)]
        if self.context.graph_fault(GraphFault::Begin) {
            return Err(CudaError::internal("injected capture begin failure"));
        }
        check("cuStreamBeginCapture", unsafe {
            cuStreamBeginCapture(self.raw, CU_STREAM_CAPTURE_MODE_RELAXED)
        })?;
        state.depth += 1;
        state.owner = Some(self.raw as usize);
        Ok(())
    }

    pub(crate) fn end_capture(&self) -> CudaResult<CudaGraph> {
        let owner = self.owner()?;
        let mut state = self.context.capture_state();
        if state.owner != Some(self.raw as usize) || state.depth == 0 {
            return Err(CudaError::internal("capture end stream owner mismatch"));
        }
        if let Err(error) = self.context.bind_to_thread() {
            state.unknown = true;
            return Err(error);
        }
        let mut raw = std::ptr::null_mut();
        let code = unsafe { cuStreamEndCapture(self.raw, &mut raw) };
        // End the real driver capture before withholding its result. The hook
        // tests unknown evidence without leaving the primary context capturing.
        #[cfg(test)]
        let code = if self.context.graph_fault(GraphFault::End) {
            3
        } else {
            code
        };
        state.end_result(code, !raw.is_null());
        drop(state);
        let graph = CudaGraph { raw, owner };
        check("cuStreamEndCapture", code)?;
        if raw.is_null() {
            return Err(CudaError::internal(
                "capture ended without a graph; completion unknown",
            ));
        }
        Ok(graph)
    }
}

impl Drop for CudaStream {
    fn drop(&mut self) {
        if self.context.graph_completion_unknown() {
            std::mem::forget(Arc::clone(&self.context));
            return;
        }
        let _ = self.synchronize();
        if self.owned && !self.raw.is_null() {
            let _ = check("cuStreamDestroy", unsafe { cuStreamDestroy_v2(self.raw) });
        }
    }
}

#[derive(Debug)]
pub struct CudaEvent {
    raw: CuEvent,
    context: Arc<CudaContext>,
}

pub(crate) struct CudaRetirementEvent {
    raw: CuEvent,
    context: CuContext,
}

unsafe impl Send for CudaRetirementEvent {}
unsafe impl Sync for CudaRetirementEvent {}

impl CudaRetirementEvent {
    pub(crate) fn query(&self) -> CudaResult<bool> {
        check("cuCtxSetCurrent", unsafe { cuCtxSetCurrent(self.context) })?;
        match unsafe { cuEventQuery(self.raw) } {
            CUDA_SUCCESS => Ok(true),
            CUDA_ERROR_NOT_READY => Ok(false),
            code => Err(CudaError::from_code("cuEventQuery", code)),
        }
    }

    pub(crate) fn synchronize(&self) -> CudaResult<()> {
        check("cuCtxSetCurrent", unsafe { cuCtxSetCurrent(self.context) })?;
        check("cuEventSynchronize", unsafe {
            cuEventSynchronize(self.raw)
        })
    }
}

impl fmt::Debug for CudaRetirementEvent {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("CudaRetirementEvent")
            .field("raw", &self.raw)
            .finish_non_exhaustive()
    }
}

impl Drop for CudaRetirementEvent {
    fn drop(&mut self) {
        let _ = check("cuCtxSetCurrent", unsafe { cuCtxSetCurrent(self.context) });
        let _ = check("cuEventDestroy", unsafe { cuEventDestroy_v2(self.raw) });
    }
}

unsafe impl Send for CudaEvent {}
unsafe impl Sync for CudaEvent {}

impl CudaEvent {
    pub(crate) fn check_context(
        &self,
        expected: &Arc<CudaContext>,
        operation: &'static str,
    ) -> CudaResult<()> {
        if !Arc::ptr_eq(&self.context, expected) {
            return Err(CudaError::internal(format!(
                "{operation}: CUDA event owner mismatch (event ordinal={}, expected ordinal={})",
                self.context.ordinal(),
                expected.ordinal(),
            )));
        }
        Ok(())
    }

    pub fn record(&self, stream: &CudaStream) -> CudaResult<()> {
        self.context.bind_to_thread()?;
        check("cuEventRecord", unsafe {
            cuEventRecord(self.raw, stream.raw)
        })
    }

    pub fn synchronize(&self) -> CudaResult<()> {
        self.context.bind_to_thread()?;
        check("cuEventSynchronize", unsafe {
            cuEventSynchronize(self.raw)
        })
    }

    pub fn query(&self) -> CudaResult<bool> {
        self.context.bind_to_thread()?;
        match unsafe { cuEventQuery(self.raw) } {
            CUDA_SUCCESS => Ok(true),
            CUDA_ERROR_NOT_READY => Ok(false),
            code => Err(CudaError::from_code("cuEventQuery", code)),
        }
    }

    pub fn elapsed(&self, end: &Self) -> CudaResult<f32> {
        let mut milliseconds = 0.0;
        check("cuEventElapsedTime", unsafe {
            cuEventElapsedTime(&mut milliseconds, self.raw, end.raw)
        })?;
        Ok(milliseconds)
    }
}

impl Drop for CudaEvent {
    fn drop(&mut self) {
        let _ = self.context.bind_to_thread();
        let _ = check("cuEventDestroy", unsafe { cuEventDestroy_v2(self.raw) });
    }
}

/// Physical memory tier backing a CUDA buffer.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MemoryTier {
    /// Device memory owned by the canonical segmented allocator.
    Device,
    /// CUDA managed memory explicitly selected for unified addressing.
    Managed,
}

enum DeviceAllocation {
    Allocator(Arc<CudaDeviceBlock>),
    Managed {
        ptr: DevicePtr,
        bytes: usize,
        context: Arc<CudaContext>,
    },
}

impl DeviceAllocation {
    fn bytes(&self) -> usize {
        match self {
            Self::Allocator(block) => block.requested_bytes(),
            Self::Managed { bytes, .. } => *bytes,
        }
    }

    fn context(&self) -> &Arc<CudaContext> {
        match self {
            Self::Allocator(block) => block.context(),
            Self::Managed { context, .. } => context,
        }
    }

    const fn memory_tier(&self) -> MemoryTier {
        match self {
            Self::Allocator(_) => MemoryTier::Device,
            Self::Managed { .. } => MemoryTier::Managed,
        }
    }
}

impl Drop for DeviceAllocation {
    fn drop(&mut self) {
        if let Self::Managed { ptr, context, .. } = self
            && *ptr != 0
        {
            if context.is_capturing() {
                std::mem::forget(Arc::clone(context));
                return;
            }
            let _ = context.bind_to_thread();
            let _ = check("cuMemFreeManaged", unsafe { cuMemFree_v2(*ptr) });
        }
    }
}

unsafe impl Send for DeviceAllocation {}
unsafe impl Sync for DeviceAllocation {}

/// A checked view into a shared CUDA allocation.
///
/// Root buffers and disjoint slices share one allocation owner, so large weight
/// arenas can expose ordinary typed kernel arguments without creating one CUDA
/// allocation per tensor.
pub struct DeviceBuffer<T: DeviceCopy> {
    ptr: DevicePtr,
    len: usize,
    allocation: Arc<DeviceAllocation>,
    _element: PhantomData<T>,
}

unsafe impl<T: DeviceCopy> Send for DeviceBuffer<T> {}
unsafe impl<T: DeviceCopy> Sync for DeviceBuffer<T> {}

impl<T: DeviceCopy> fmt::Debug for DeviceBuffer<T> {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("DeviceBuffer")
            .field("ptr", &format_args!("{:#x}", self.ptr))
            .field("len", &self.len)
            .field("allocation_bytes", &self.allocation.bytes())
            .field("memory_tier", &self.memory_tier())
            .finish_non_exhaustive()
    }
}

impl<T: DeviceCopy> DeviceBuffer<T> {
    pub fn from_host(stream: &CudaStream, values: &[T]) -> CudaResult<Self> {
        let buffer = unsafe { Self::uninitialized_async(stream, values.len())? };
        buffer.copy_from_host(stream, values)?;
        stream.synchronize()?;
        Ok(buffer)
    }

    ///
    /// # Safety
    /// All device buffers must be valid allocations sized for the shapes passed,
    /// and the launch must be enqueued on a stream belonging to this context.
    pub unsafe fn from_pinned_host(
        stream: &CudaStream,
        values: &PinnedHostBuffer<T>,
    ) -> CudaResult<Self> {
        let buffer = unsafe { Self::uninitialized_async(stream, values.len())? };
        unsafe { buffer.copy_from_pinned_host_async(stream, values)? };
        Ok(buffer)
    }

    pub fn zeroed(stream: &CudaStream, len: usize) -> CudaResult<Self> {
        let buffer = unsafe { Self::uninitialized_async(stream, len)? };
        stream.context.bind_to_thread()?;
        if buffer.num_bytes() != 0 {
            check("cuMemsetD8Async", unsafe {
                cuMemsetD8Async(buffer.ptr, 0, buffer.num_bytes(), stream.raw)
            })?;
        }
        Ok(buffer)
    }

    ///
    /// # Safety
    /// All device buffers must be valid allocations sized for the shapes passed,
    /// and the launch must be enqueued on a stream belonging to this context.
    pub unsafe fn uninitialized_async(stream: &CudaStream, len: usize) -> CudaResult<Self> {
        let bytes = allocation_bytes::<T>(len)?;
        let block = stream
            .context
            .allocator
            .allocate(bytes, std::mem::align_of::<T>())?;
        Ok(Self {
            ptr: block.ptr(),
            len,
            allocation: Arc::new(DeviceAllocation::Allocator(block)),
            _element: PhantomData,
        })
    }

    ///
    /// # Safety
    /// All device buffers must be valid allocations sized for the shapes passed,
    /// and the launch must be enqueued on a stream belonging to this context.
    pub unsafe fn managed(context: &Arc<CudaContext>, len: usize) -> CudaResult<Self> {
        let bytes = allocation_bytes::<T>(len)?;
        let capture_state = context.capture_state();
        if capture_state.blocks_allocation() {
            return Err(CudaError::internal(
                "CUDA managed memory cannot allocate during graph capture",
            ));
        }
        context.bind_to_thread()?;
        let mut ptr = 0;
        if bytes != 0 {
            check("cuMemAllocManaged", unsafe {
                cuMemAllocManaged(&mut ptr, bytes, CU_MEM_ATTACH_GLOBAL)
            })?;
            check("cuMemAdvise", unsafe {
                cuMemAdvise(ptr, bytes, CU_MEM_ADVISE_SET_READ_MOSTLY, context.device())
            })?;
        }
        drop(capture_state);
        Ok(Self {
            ptr,
            len,
            allocation: Arc::new(DeviceAllocation::Managed {
                ptr,
                bytes,
                context: Arc::clone(context),
            }),
            _element: PhantomData,
        })
    }

    pub fn slice(&self, offset: usize, len: usize) -> CudaResult<Self> {
        let end = offset
            .checked_add(len)
            .ok_or_else(|| CudaError::from_code("device buffer slice overflow", 1))?;
        if end > self.len {
            return Err(CudaError::from_code("device buffer slice out of bounds", 1));
        }
        let byte_offset = offset
            .checked_mul(std::mem::size_of::<T>())
            .ok_or_else(|| CudaError::from_code("device buffer byte offset overflow", 1))?;
        let ptr = self
            .ptr
            .checked_add(byte_offset as u64)
            .ok_or_else(|| CudaError::from_code("device buffer pointer overflow", 1))?;
        Ok(Self {
            ptr,
            len,
            allocation: Arc::clone(&self.allocation),
            _element: PhantomData,
        })
    }

    pub fn cu_deviceptr(&self) -> DevicePtr {
        self.ptr
    }

    pub fn len(&self) -> usize {
        self.len
    }

    pub fn is_empty(&self) -> bool {
        self.len == 0
    }

    pub fn num_bytes(&self) -> usize {
        self.len.saturating_mul(std::mem::size_of::<T>())
    }

    pub fn context(&self) -> &Arc<CudaContext> {
        self.allocation.context()
    }

    pub fn memory_tier(&self) -> MemoryTier {
        self.allocation.memory_tier()
    }

    pub(crate) fn check_context(
        &self,
        context: &Arc<CudaContext>,
        operation: &str,
    ) -> CudaResult<()> {
        // Device ordinals (and retained primary-context handles) can match while
        // allocation/stream owners differ. Ordinary typed copies require one owner.
        if !Arc::ptr_eq(self.context(), context) {
            return Err(CudaError::internal(format!(
                "{operation}: CUDA buffer owner mismatch (buffer ordinal={}, expected ordinal={})",
                self.context().ordinal(),
                context.ordinal(),
            )));
        }
        Ok(())
    }

    pub fn copy_from_host(&self, stream: &CudaStream, values: &[T]) -> CudaResult<()> {
        self.check_context(&stream.context, "copy_from_host")?;
        stream.context.bind_to_thread()?;
        if values.len() != self.len {
            return Err(CudaError::from_code("host-to-device length mismatch", 1));
        }
        if self.num_bytes() == 0 {
            return Ok(());
        }
        check("cuMemcpyHtoDAsync", unsafe {
            cuMemcpyHtoDAsync_v2(
                self.ptr,
                values.as_ptr().cast(),
                self.num_bytes(),
                stream.raw,
            )
        })
    }

    ///
    /// # Safety
    /// All device buffers must be valid allocations sized for the shapes passed,
    /// and the launch must be enqueued on a stream belonging to this context.
    pub unsafe fn copy_from_pinned_host_async(
        &self,
        stream: &CudaStream,
        values: &PinnedHostBuffer<T>,
    ) -> CudaResult<()> {
        self.check_context(&stream.context, "copy_from_pinned_host_async")?;
        stream.context.bind_to_thread()?;
        if values.len() != self.len {
            return Err(CudaError::from_code(
                "pinned host-to-device length mismatch",
                1,
            ));
        }
        if self.num_bytes() == 0 {
            return Ok(());
        }
        check("cuMemcpyHtoDAsync", unsafe {
            cuMemcpyHtoDAsync_v2(
                self.ptr,
                values.as_ptr().cast(),
                self.num_bytes(),
                stream.raw,
            )
        })
    }

    pub fn to_host_vec(&self, stream: &CudaStream) -> CudaResult<Vec<T>> {
        self.check_context(&stream.context, "to_host_vec")?;
        let mut values = vec![T::default(); self.len];
        self.copy_to_host(stream, &mut values)?;
        Ok(values)
    }

    pub fn copy_to_host(&self, stream: &CudaStream, values: &mut [T]) -> CudaResult<()> {
        self.check_context(&stream.context, "copy_to_host")?;
        stream.context.bind_to_thread()?;
        if values.len() != self.len {
            return Err(CudaError::from_code("device-to-host length mismatch", 1));
        }
        if self.num_bytes() != 0 {
            check("cuMemcpyDtoHAsync", unsafe {
                cuMemcpyDtoHAsync_v2(
                    values.as_mut_ptr().cast(),
                    self.ptr,
                    self.num_bytes(),
                    stream.raw,
                )
            })?;
        }
        stream.synchronize()
    }

    ///
    /// # Safety
    /// All device buffers must be valid allocations sized for the shapes passed,
    /// and the launch must be enqueued on a stream belonging to this context.
    pub unsafe fn copy_to_pinned_host_async(
        &self,
        stream: &CudaStream,
        values: &mut PinnedHostBuffer<T>,
    ) -> CudaResult<()> {
        self.check_context(&stream.context, "copy_to_pinned_host_async")?;
        stream.context.bind_to_thread()?;
        if values.len() != self.len {
            return Err(CudaError::from_code(
                "device-to-pinned-host length mismatch",
                1,
            ));
        }
        if self.num_bytes() == 0 {
            return Ok(());
        }
        check("cuMemcpyDtoHAsync", unsafe {
            cuMemcpyDtoHAsync_v2(
                values.as_mut_ptr().cast(),
                self.ptr,
                self.num_bytes(),
                stream.raw,
            )
        })
    }
}

pub struct PinnedHostBuffer<T: DeviceCopy> {
    ptr: NonNull<T>,
    len: usize,
    bytes: usize,
    context: Arc<CudaContext>,
}

unsafe impl<T: DeviceCopy> Send for PinnedHostBuffer<T> {}
unsafe impl<T: DeviceCopy> Sync for PinnedHostBuffer<T> {}

impl<T: DeviceCopy> fmt::Debug for PinnedHostBuffer<T> {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("PinnedHostBuffer")
            .field("ptr", &self.ptr)
            .field("len", &self.len)
            .finish_non_exhaustive()
    }
}

impl<T: DeviceCopy> PinnedHostBuffer<T> {
    pub fn zeroed(context: &Arc<CudaContext>, len: usize) -> CudaResult<Self> {
        let buffer = Self::allocate(context, len)?;
        if buffer.bytes != 0 {
            unsafe { std::ptr::write_bytes(buffer.ptr.as_ptr().cast::<u8>(), 0, buffer.bytes) };
        }
        Ok(buffer)
    }

    pub fn from_slice(context: &Arc<CudaContext>, values: &[T]) -> CudaResult<Self> {
        let mut buffer = Self::allocate(context, values.len())?;
        if !values.is_empty() {
            buffer.as_mut_slice().copy_from_slice(values);
        }
        Ok(buffer)
    }

    fn allocate(context: &Arc<CudaContext>, len: usize) -> CudaResult<Self> {
        let bytes = allocation_bytes::<T>(len)?;
        let capture_state = context.capture_state();
        if capture_state.blocks_allocation() {
            return Err(CudaError::internal(
                "CUDA pinned memory cannot allocate during graph capture or unknown completion",
            ));
        }
        context.bind_to_thread()?;
        let ptr = if bytes == 0 {
            NonNull::dangling()
        } else {
            let mut ptr = std::ptr::null_mut();
            check("cuMemAllocHost", unsafe {
                cuMemAllocHost_v2(&mut ptr, bytes)
            })?;
            NonNull::new(ptr.cast::<T>())
                .ok_or_else(|| CudaError::from_code("cuMemAllocHost null pointer", 1))?
        };
        Ok(Self {
            ptr,
            len,
            bytes,
            context: Arc::clone(context),
        })
    }

    pub fn len(&self) -> usize {
        self.len
    }

    pub fn is_empty(&self) -> bool {
        self.len == 0
    }

    pub fn as_ptr(&self) -> *const T {
        self.ptr.as_ptr()
    }

    pub fn as_mut_ptr(&mut self) -> *mut T {
        self.ptr.as_ptr()
    }

    pub fn as_slice(&self) -> &[T] {
        unsafe { std::slice::from_raw_parts(self.ptr.as_ptr(), self.len) }
    }

    pub fn as_mut_slice(&mut self) -> &mut [T] {
        unsafe { std::slice::from_raw_parts_mut(self.ptr.as_ptr(), self.len) }
    }

    pub fn context(&self) -> &Arc<CudaContext> {
        &self.context
    }

    pub fn device_pointer(&self) -> CudaResult<DevicePtr> {
        let mut ptr = 0;
        check("cuMemHostGetDevicePointer", unsafe {
            cuMemHostGetDevicePointer_v2(&mut ptr, self.ptr.as_ptr().cast(), 0)
        })?;
        Ok(ptr)
    }
}

impl<T: DeviceCopy> Deref for PinnedHostBuffer<T> {
    type Target = [T];

    fn deref(&self) -> &Self::Target {
        self.as_slice()
    }
}

impl<T: DeviceCopy> DerefMut for PinnedHostBuffer<T> {
    fn deref_mut(&mut self) -> &mut Self::Target {
        self.as_mut_slice()
    }
}

impl<T: DeviceCopy> Drop for PinnedHostBuffer<T> {
    fn drop(&mut self) {
        if self.bytes != 0 {
            if self.context.is_capturing() {
                std::mem::forget(Arc::clone(&self.context));
                return;
            }
            let _ = self.context.bind_to_thread();
            let _ = check("cuMemFreeHost", unsafe {
                cuMemFreeHost(self.ptr.as_ptr().cast())
            });
        }
    }
}

pub(crate) struct CudaGraph {
    raw: CuGraph,
    owner: Arc<CudaStream>,
}

impl CudaGraph {
    pub(crate) fn instantiate(&self) -> CudaResult<CudaGraphExec> {
        self.owner.context.check_graph_ready()?;
        self.owner.context.bind_to_thread()?;
        #[cfg(test)]
        if self.owner.context.graph_fault(GraphFault::Instantiate) {
            return Err(CudaError::internal("injected graph instantiate failure"));
        }
        let mut raw = std::ptr::null_mut();
        check("cuGraphInstantiate", unsafe {
            cuGraphInstantiateWithFlags(&mut raw, self.raw, 0)
        })?;
        Ok(CudaGraphExec {
            raw,
            owner: Arc::clone(&self.owner),
        })
    }
}

impl Drop for CudaGraph {
    fn drop(&mut self) {
        if !self.raw.is_null() {
            if self.owner.context.graph_completion_unknown()
                || self.owner.context.bind_to_thread().is_err()
            {
                // Preserve native custody and context lifetime without claiming a
                // process exit or unrelated sync proved graph retirement.
                std::mem::forget(Arc::clone(&self.owner));
                return;
            }
            let _ = check("cuGraphDestroy", unsafe { cuGraphDestroy(self.raw) });
        }
    }
}

pub(crate) struct CudaGraphExec {
    raw: CuGraphExec,
    owner: Arc<CudaStream>,
}

impl CudaGraphExec {
    pub(crate) fn precheck(&self, stream: &CudaStream) -> CudaResult<()> {
        if !Arc::ptr_eq(&self.owner.context, stream.context())
            || !std::ptr::eq(self.owner.as_ref(), stream)
        {
            return Err(CudaError::internal(
                "CUDA graph context/stream owner mismatch",
            ));
        }
        self.owner.context.check_graph_ready()
    }

    pub(crate) fn launch(&self, stream: &CudaStream) -> CudaResult<()> {
        self.precheck(stream)?;
        self.owner.context.bind_to_thread()?;
        #[cfg(test)]
        if self.owner.context.graph_fault(GraphFault::Launch) {
            self.owner.context.mark_graph_unknown();
            return Err(CudaError::internal(
                "injected graph launch completion unknown",
            ));
        }
        let result = check("cuGraphLaunch", unsafe {
            cuGraphLaunch(self.raw, stream.raw)
        });
        if result.is_err() {
            self.owner.context.mark_graph_unknown();
        }
        result
    }

    pub(crate) fn upload(&self, stream: &CudaStream) -> CudaResult<()> {
        self.precheck(stream)?;
        self.owner.context.bind_to_thread()?;
        #[cfg(test)]
        if self.owner.context.graph_fault(GraphFault::Upload) {
            self.owner.context.mark_graph_unknown();
            return Err(CudaError::internal(
                "injected graph upload completion unknown",
            ));
        }
        let result = check("cuGraphUpload", unsafe {
            cuGraphUpload(self.raw, stream.raw)
        });
        if result.is_err() {
            self.owner.context.mark_graph_unknown();
        }
        result
    }
}

impl Drop for CudaGraphExec {
    fn drop(&mut self) {
        if !self.raw.is_null() {
            if self.owner.context.graph_completion_unknown()
                || self.owner.context.bind_to_thread().is_err()
            {
                std::mem::forget(Arc::clone(&self.owner));
                return;
            }
            let _ = check("cuGraphExecDestroy", unsafe {
                cuGraphExecDestroy(self.raw)
            });
        }
    }
}

pub(crate) fn copy_device_to_device(
    stream: &CudaStream,
    destination: DevicePtr,
    source: DevicePtr,
    bytes: usize,
) -> CudaResult<()> {
    stream.context.bind_to_thread()?;
    if bytes == 0 {
        return Ok(());
    }
    check("cuMemcpyDtoDAsync", unsafe {
        cuMemcpyDtoDAsync_v2(destination, source, bytes, stream.raw)
    })
}

pub(crate) fn copy_host_to_device(
    stream: &CudaStream,
    destination: DevicePtr,
    source: *const c_void,
    bytes: usize,
) -> CudaResult<()> {
    stream.context.bind_to_thread()?;
    if bytes == 0 {
        return Ok(());
    }
    check("cuMemcpyHtoDAsync", unsafe {
        cuMemcpyHtoDAsync_v2(destination, source, bytes, stream.raw)
    })
}

pub(crate) fn copy_device_to_host(
    stream: &CudaStream,
    destination: *mut c_void,
    source: DevicePtr,
    bytes: usize,
) -> CudaResult<()> {
    stream.context.bind_to_thread()?;
    if bytes == 0 {
        return Ok(());
    }
    check("cuMemcpyDtoHAsync", unsafe {
        cuMemcpyDtoHAsync_v2(destination, source, bytes, stream.raw)
    })
}

/// Copy a pinned subrange into the entire checked device view.
///
/// # Safety
/// Keep both allocations alive and the pinned source immutable until the copy
/// completes. Order device readers/writers around this copy on their streams.
pub(crate) unsafe fn copy_host_to_device_pinned_range<T: DeviceCopy>(
    stream: &CudaStream,
    destination: &DeviceBuffer<T>,
    source: &PinnedHostBuffer<T>,
    source_offset: usize,
) -> CudaResult<()> {
    destination.check_context(stream.context(), "pinned H2D destination")?;
    check_pinned_range(source, stream.context(), source_offset, destination.len())?;
    let bytes = allocation_bytes::<T>(destination.len())?;
    // SAFETY: the checked range is within the pinned allocation.
    let source = unsafe { source.as_ptr().add(source_offset) };
    copy_host_to_device(stream, destination.cu_deviceptr(), source.cast(), bytes)
}

/// Copy the entire checked device view into a pinned subrange.
///
/// # Safety
/// Keep both allocations alive and do not access the pinned destination until
/// the copy completes. The device source must not be overwritten during DMA.
pub(crate) unsafe fn copy_device_to_pinned_host_range<T: DeviceCopy>(
    stream: &CudaStream,
    destination: &mut PinnedHostBuffer<T>,
    destination_offset: usize,
    source: &DeviceBuffer<T>,
) -> CudaResult<()> {
    source.check_context(stream.context(), "pinned D2H source")?;
    check_pinned_range(
        destination,
        stream.context(),
        destination_offset,
        source.len(),
    )?;
    let bytes = allocation_bytes::<T>(source.len())?;
    // SAFETY: the checked range is within the pinned allocation.
    let destination = unsafe { destination.as_mut_ptr().add(destination_offset) };
    copy_device_to_host(stream, destination.cast(), source.cu_deviceptr(), bytes)
}

fn check_pinned_range<T: DeviceCopy>(
    pinned: &PinnedHostBuffer<T>,
    context: &Arc<CudaContext>,
    offset: usize,
    elements: usize,
) -> CudaResult<()> {
    if !Arc::ptr_eq(pinned.context(), context) {
        return Err(CudaError::internal("pinned transfer owner mismatch"));
    }
    let end = offset
        .checked_add(elements)
        .ok_or_else(|| CudaError::internal("pinned transfer range overflow"))?;
    if end > pinned.len() || allocation_bytes::<T>(end)? > isize::MAX as usize {
        return Err(CudaError::internal("pinned transfer range out of bounds"));
    }
    Ok(())
}

pub(crate) fn memset_u32(
    stream: &CudaStream,
    destination: DevicePtr,
    value: u32,
    elements: usize,
) -> CudaResult<()> {
    stream.context.bind_to_thread()?;
    if elements == 0 {
        return Ok(());
    }
    check("cuMemsetD32Async", unsafe {
        cuMemsetD32Async(destination, value, elements, stream.raw)
    })
}

pub(crate) fn alloc_host(bytes: usize) -> CudaResult<*mut c_void> {
    let mut ptr = std::ptr::null_mut();
    if bytes != 0 {
        check("cuMemAllocHost", unsafe {
            cuMemAllocHost_v2(&mut ptr, bytes)
        })?;
    }
    Ok(ptr)
}

pub(crate) fn free_host(ptr: *mut c_void) -> CudaResult<()> {
    if ptr.is_null() {
        Ok(())
    } else {
        check("cuMemFreeHost", unsafe { cuMemFreeHost(ptr) })
    }
}

pub(crate) fn host_device_pointer(ptr: *mut c_void) -> CudaResult<DevicePtr> {
    let mut device = 0;
    check("cuMemHostGetDevicePointer", unsafe {
        cuMemHostGetDevicePointer_v2(&mut device, ptr, 0)
    })?;
    Ok(device)
}

fn allocation_bytes<T>(len: usize) -> CudaResult<usize> {
    len.checked_mul(std::mem::size_of::<T>())
        .ok_or_else(|| CudaError::from_code("CUDA allocation size overflow", 1))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cuda::allocator::AllocationCommitHook;
    use std::sync::Barrier;
    use std::sync::atomic::{AtomicBool, Ordering};
    use std::time::Duration;

    #[test]
    fn typed_slices_keep_allocator_block_alive() {
        let Ok(context) = CudaContext::new(0) else {
            return;
        };
        let stream = context.default_stream();
        let root = DeviceBuffer::<u32>::zeroed(&stream, 1024).unwrap();
        let root_ptr = root.cu_deviceptr();
        let slice = root.slice(128, 256).unwrap();
        assert_eq!(slice.cu_deviceptr(), root_ptr + 128 * 4);
        drop(root);

        let other = DeviceBuffer::<u32>::zeroed(&stream, 1024).unwrap();
        assert_ne!(other.cu_deviceptr(), root_ptr);
        drop(slice);
        drop(other);
        stream.synchronize().unwrap();
        context.allocator.poll_retirements();
    }

    #[test]
    fn retirement_never_reuses_a_block_before_all_streams_finish() {
        let Ok(context) = CudaContext::new(0) else {
            return;
        };
        let producer = context.new_stream().unwrap();
        let allocator_stream = context.new_stream().unwrap();
        let block = DeviceBuffer::<u8>::zeroed(&producer, 4096).unwrap();
        let retired_ptr = block.cu_deviceptr();
        let release = Arc::new(AtomicBool::new(false));
        let callback_release = Arc::clone(&release);
        producer
            .launch_host_function(move || {
                while !callback_release.load(Ordering::Acquire) {
                    std::thread::sleep(Duration::from_millis(1));
                }
            })
            .unwrap();
        drop(block);

        let before_completion = DeviceBuffer::<u8>::zeroed(&allocator_stream, 4096).unwrap();
        assert_ne!(before_completion.cu_deviceptr(), retired_ptr);
        assert_eq!(context.allocator_metrics().pending_retirement_blocks, 1);

        release.store(true, Ordering::Release);
        producer.synchronize().unwrap();
        context.allocator.poll_retirements();
        let after_completion = DeviceBuffer::<u8>::zeroed(&allocator_stream, 4096).unwrap();
        assert_eq!(after_completion.cu_deviceptr(), retired_ptr);
    }

    #[test]
    fn graph_capture_rejects_allocator_growth() {
        let Ok(context) = CudaContext::new(0) else {
            return;
        };
        let stream = context.new_stream().unwrap();
        stream.begin_capture().unwrap();
        let result = DeviceBuffer::<u8>::zeroed(&stream, 4096);
        let _ = stream.end_capture();
        let error = match result {
            Ok(_) => panic!("allocation during capture must fail"),
            Err(error) => error,
        };
        assert!(
            error
                .to_string()
                .contains("cannot allocate during graph capture")
        );
        assert_eq!(context.allocator_metrics().driver_allocations, 0);
    }

    #[test]
    fn graph_capture_rejects_reusing_a_free_block() {
        let Ok(context) = CudaContext::new(0) else {
            return;
        };
        let stream = context.new_stream().unwrap();
        let buffer = DeviceBuffer::<u8>::zeroed(&stream, 4096).unwrap();
        drop(buffer);
        stream.synchronize().unwrap();
        context.allocator.poll_retirements();
        let before = context.allocator_metrics();
        assert!(before.free_bytes >= 4096);

        stream.begin_capture().unwrap();
        let result = DeviceBuffer::<u8>::zeroed(&stream, 4096);
        let _ = stream.end_capture();
        let error = match result {
            Ok(_) => panic!("free-block reuse during capture must fail"),
            Err(error) => error,
        };
        assert!(
            error
                .to_string()
                .contains("cannot allocate during graph capture")
        );
        let after = context.allocator_metrics();
        assert_eq!(after.reuse_allocations, before.reuse_allocations);
        assert_eq!(after.driver_allocations, before.driver_allocations);
        assert_eq!(after.live_requested_bytes, 0);
    }

    #[test]
    fn shutdown_wins_before_final_allocation_commit() {
        let Ok(context) = CudaContext::new(0) else {
            return;
        };
        let reached = Arc::new(Barrier::new(2));
        let resume = Arc::new(Barrier::new(2));
        context
            .allocator
            .set_allocation_commit_hook(AllocationCommitHook {
                reached: Arc::clone(&reached),
                resume: Arc::clone(&resume),
            });

        let worker_context = Arc::clone(&context);
        let allocation = std::thread::spawn(move || {
            let stream = worker_context.default_stream();
            DeviceBuffer::<u8>::zeroed(&stream, 4096)
        });
        reached.wait();
        context.shutdown_allocator();
        resume.wait();

        let error = allocation
            .join()
            .expect("allocation thread")
            .expect_err("shutdown before commit must reject allocation");
        assert!(error.to_string().contains("shut down"));
        let metrics = context.allocator_metrics();
        assert_eq!(metrics.allocation_requests, 0);
        assert_eq!(metrics.live_requested_bytes, 0);
        assert_eq!(metrics.driver_allocations, 0);
    }

    #[test]
    fn graph_capture_rejects_managed_allocations() {
        let Ok(context) = CudaContext::new(0) else {
            return;
        };
        let stream = context.new_stream().unwrap();
        stream.begin_capture().unwrap();
        let result = unsafe { DeviceBuffer::<u8>::managed(&context, 1) };
        let _ = stream.end_capture();
        let error = result.expect_err("managed allocation during capture must fail");
        assert!(
            error
                .to_string()
                .contains("cannot allocate during graph capture")
        );
    }

    #[test]
    fn device_and_managed_allocations_report_distinct_memory_tiers() {
        let Ok(context) = CudaContext::new(0) else {
            return;
        };
        let stream = context.default_stream();
        let device = DeviceBuffer::<u8>::zeroed(&stream, 1).unwrap();
        let managed = unsafe { DeviceBuffer::<u8>::managed(&context, 1) }.unwrap();
        assert_eq!(device.memory_tier(), MemoryTier::Device);
        assert_eq!(managed.memory_tier(), MemoryTier::Managed);
    }

    #[test]
    fn explicit_shutdown_preserves_capture_retirements() {
        let Ok(context) = CudaContext::new(0) else {
            return;
        };
        let stream = context.new_stream().unwrap();
        let buffer = DeviceBuffer::<u8>::zeroed(&stream, 4096).unwrap();
        stream.synchronize().unwrap();
        stream.begin_capture().unwrap();
        drop(buffer);
        let _graph = stream.end_capture().unwrap();

        let captured = context.allocator_metrics();
        assert_eq!(captured.capture_retirement_bytes, 4096);
        context.shutdown_allocator();
        let shutdown = context.allocator_metrics();
        assert_eq!(shutdown.capture_retirement_bytes, 4096);
        assert_eq!(shutdown.reserved_bytes, captured.reserved_bytes);
        assert_eq!(shutdown.driver_frees, 0);
    }

    #[test]
    fn allocator_metrics_and_trim_track_driver_segments() {
        let Ok(context) = CudaContext::new(0) else {
            return;
        };
        let stream = context.default_stream();
        let buffer = DeviceBuffer::<u8>::zeroed(&stream, 257).unwrap();
        let live = context.allocator_metrics();
        assert_eq!(live.allocation_requests, 1);
        assert_eq!(live.requested_bytes, 257);
        assert_eq!(live.granted_bytes, 512);
        assert_eq!(live.live_requested_bytes, 257);
        assert_eq!(live.live_granted_bytes, 512);
        assert_eq!(live.driver_allocations, 1);
        assert!(live.reserved_bytes >= live.live_granted_bytes);
        assert!(live.internal_fragmentation > 0.0);

        drop(buffer);
        stream.synchronize().unwrap();
        context.allocator.poll_retirements();
        let released = context.trim_allocator().unwrap();
        let trimmed = context.allocator_metrics();
        assert!(released > 0);
        assert_eq!(trimmed.reserved_bytes, 0);
        assert_eq!(trimmed.driver_frees, 1);
        assert_eq!(trimmed.live_requested_bytes, 0);
    }
}

#[cfg(test)]
mod capture_state_tests {
    use super::*;

    #[test]
    fn end_evidence_controls_depth_and_unknown_is_sticky() {
        for (code, graph, ended) in [
            (0, true, true),
            (901, false, true),
            (3, false, false),
            (1, false, false),
            (0, false, false),
        ] {
            let mut state = CaptureState {
                depth: 1,
                owner: Some(7),
                unknown: false,
            };
            state.end_result(code, graph);
            assert_eq!(state.depth, if ended { 0 } else { 1 });
            assert_eq!(state.unknown, !ended);
            assert_eq!(state.blocks_allocation(), !ended);
            if !ended {
                state.end_result(0, true);
                assert!(state.unknown);
                assert_eq!(
                    state.depth, 1,
                    "later local success is not unknown retirement evidence"
                );
            }
        }
    }
}
